// [ 4, 6, ,-1, 8, -45] => [4, 6, 0, 8, 0]

function zeroOutNegativeValues(arr){
    // ITERATE THROUGH THE ARRAY
        // CHECK TO SEE IF THE VALUE IS NEGATIVE
            // SET THE VALUE TO ZERO
    // RETURN THE ARRAY
}


function printMaxMinAverageArrayVals(arr){
    // CREATE VARIABLE TO KEEP TRACK OF MAX
    // CREATE VARIABLE TO KEEP TRACK OF MIN
    // CREATE VARIABLE TO KEEP TRACK OF TOTAL / SUM
    // ITERATE THROUGH THE ARRAY
        // CHECK TO SEE IF THE VALUE IS GREATER THAN THE CURRENT MAX
            // THE VALUE BECOMES THE NEW MAX
        // CHECK TO SEE IF THE VALUE IS LESS THAN THE CURRENT MIN
            // THE VALUES BECOMES THE NEW MIN
        // ADD THE VALUE TO THE SUM / TOTAL
    // PRINT THE MAX, MIN, THE AVERAGE
}